// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"
	"io"
	"net/http"

	"github.com/ministryofjustice/opg-scanning/internal/auth"
	"github.com/ministryofjustice/opg-scanning/internal/sirius"
	mock "github.com/stretchr/testify/mock"
)

// newMockAuth creates a new instance of mockAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAuth {
	mock := &mockAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockAuth is an autogenerated mock type for the Auth type
type mockAuth struct {
	mock.Mock
}

type mockAuth_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAuth) EXPECT() *mockAuth_Expecter {
	return &mockAuth_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type mockAuth
func (_mock *mockAuth) Authenticate(w http.ResponseWriter, r *http.Request) (auth.AuthenticatedUser, error) {
	ret := _mock.Called(w, r)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 auth.AuthenticatedUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request) (auth.AuthenticatedUser, error)); ok {
		return returnFunc(w, r)
	}
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request) auth.AuthenticatedUser); ok {
		r0 = returnFunc(w, r)
	} else {
		r0 = ret.Get(0).(auth.AuthenticatedUser)
	}
	if returnFunc, ok := ret.Get(1).(func(http.ResponseWriter, *http.Request) error); ok {
		r1 = returnFunc(w, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAuth_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type mockAuth_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *mockAuth_Expecter) Authenticate(w interface{}, r interface{}) *mockAuth_Authenticate_Call {
	return &mockAuth_Authenticate_Call{Call: _e.mock.On("Authenticate", w, r)}
}

func (_c *mockAuth_Authenticate_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *mockAuth_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockAuth_Authenticate_Call) Return(authenticatedUser auth.AuthenticatedUser, err error) *mockAuth_Authenticate_Call {
	_c.Call.Return(authenticatedUser, err)
	return _c
}

func (_c *mockAuth_Authenticate_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request) (auth.AuthenticatedUser, error)) *mockAuth_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// Check provides a mock function for the type mockAuth
func (_mock *mockAuth) Check(next http.Handler) http.HandlerFunc {
	ret := _mock.Called(next)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 http.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func(http.Handler) http.HandlerFunc); ok {
		r0 = returnFunc(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}
	return r0
}

// mockAuth_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type mockAuth_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - next http.Handler
func (_e *mockAuth_Expecter) Check(next interface{}) *mockAuth_Check_Call {
	return &mockAuth_Check_Call{Call: _e.mock.On("Check", next)}
}

func (_c *mockAuth_Check_Call) Run(run func(next http.Handler)) *mockAuth_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.Handler
		if args[0] != nil {
			arg0 = args[0].(http.Handler)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockAuth_Check_Call) Return(handlerFunc http.HandlerFunc) *mockAuth_Check_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *mockAuth_Check_Call) RunAndReturn(run func(next http.Handler) http.HandlerFunc) *mockAuth_Check_Call {
	_c.Call.Return(run)
	return _c
}

// newMockAwsClient creates a new instance of mockAwsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAwsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAwsClient {
	mock := &mockAwsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockAwsClient is an autogenerated mock type for the AwsClient type
type mockAwsClient struct {
	mock.Mock
}

type mockAwsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAwsClient) EXPECT() *mockAwsClient_Expecter {
	return &mockAwsClient_Expecter{mock: &_m.Mock}
}

// PersistFormData provides a mock function for the type mockAwsClient
func (_mock *mockAwsClient) PersistFormData(ctx context.Context, body io.Reader, docType string) (string, error) {
	ret := _mock.Called(ctx, body, docType)

	if len(ret) == 0 {
		panic("no return value specified for PersistFormData")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, string) (string, error)); ok {
		return returnFunc(ctx, body, docType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, string) string); ok {
		r0 = returnFunc(ctx, body, docType)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.Reader, string) error); ok {
		r1 = returnFunc(ctx, body, docType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAwsClient_PersistFormData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PersistFormData'
type mockAwsClient_PersistFormData_Call struct {
	*mock.Call
}

// PersistFormData is a helper method to define mock.On call
//   - ctx context.Context
//   - body io.Reader
//   - docType string
func (_e *mockAwsClient_Expecter) PersistFormData(ctx interface{}, body interface{}, docType interface{}) *mockAwsClient_PersistFormData_Call {
	return &mockAwsClient_PersistFormData_Call{Call: _e.mock.On("PersistFormData", ctx, body, docType)}
}

func (_c *mockAwsClient_PersistFormData_Call) Run(run func(ctx context.Context, body io.Reader, docType string)) *mockAwsClient_PersistFormData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAwsClient_PersistFormData_Call) Return(s string, err error) *mockAwsClient_PersistFormData_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockAwsClient_PersistFormData_Call) RunAndReturn(run func(ctx context.Context, body io.Reader, docType string) (string, error)) *mockAwsClient_PersistFormData_Call {
	_c.Call.Return(run)
	return _c
}

// PersistSetData provides a mock function for the type mockAwsClient
func (_mock *mockAwsClient) PersistSetData(ctx context.Context, body []byte) (string, error) {
	ret := _mock.Called(ctx, body)

	if len(ret) == 0 {
		panic("no return value specified for PersistSetData")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (string, error)); ok {
		return returnFunc(ctx, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) string); ok {
		r0 = returnFunc(ctx, body)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAwsClient_PersistSetData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PersistSetData'
type mockAwsClient_PersistSetData_Call struct {
	*mock.Call
}

// PersistSetData is a helper method to define mock.On call
//   - ctx context.Context
//   - body []byte
func (_e *mockAwsClient_Expecter) PersistSetData(ctx interface{}, body interface{}) *mockAwsClient_PersistSetData_Call {
	return &mockAwsClient_PersistSetData_Call{Call: _e.mock.On("PersistSetData", ctx, body)}
}

func (_c *mockAwsClient_PersistSetData_Call) Run(run func(ctx context.Context, body []byte)) *mockAwsClient_PersistSetData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockAwsClient_PersistSetData_Call) Return(s string, err error) *mockAwsClient_PersistSetData_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockAwsClient_PersistSetData_Call) RunAndReturn(run func(ctx context.Context, body []byte) (string, error)) *mockAwsClient_PersistSetData_Call {
	_c.Call.Return(run)
	return _c
}

// QueueSetForProcessing provides a mock function for the type mockAwsClient
func (_mock *mockAwsClient) QueueSetForProcessing(ctx context.Context, scannedCaseResponse *sirius.ScannedCaseResponse, fileName string) (string, error) {
	ret := _mock.Called(ctx, scannedCaseResponse, fileName)

	if len(ret) == 0 {
		panic("no return value specified for QueueSetForProcessing")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sirius.ScannedCaseResponse, string) (string, error)); ok {
		return returnFunc(ctx, scannedCaseResponse, fileName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sirius.ScannedCaseResponse, string) string); ok {
		r0 = returnFunc(ctx, scannedCaseResponse, fileName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sirius.ScannedCaseResponse, string) error); ok {
		r1 = returnFunc(ctx, scannedCaseResponse, fileName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAwsClient_QueueSetForProcessing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueueSetForProcessing'
type mockAwsClient_QueueSetForProcessing_Call struct {
	*mock.Call
}

// QueueSetForProcessing is a helper method to define mock.On call
//   - ctx context.Context
//   - scannedCaseResponse *sirius.ScannedCaseResponse
//   - fileName string
func (_e *mockAwsClient_Expecter) QueueSetForProcessing(ctx interface{}, scannedCaseResponse interface{}, fileName interface{}) *mockAwsClient_QueueSetForProcessing_Call {
	return &mockAwsClient_QueueSetForProcessing_Call{Call: _e.mock.On("QueueSetForProcessing", ctx, scannedCaseResponse, fileName)}
}

func (_c *mockAwsClient_QueueSetForProcessing_Call) Run(run func(ctx context.Context, scannedCaseResponse *sirius.ScannedCaseResponse, fileName string)) *mockAwsClient_QueueSetForProcessing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sirius.ScannedCaseResponse
		if args[1] != nil {
			arg1 = args[1].(*sirius.ScannedCaseResponse)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAwsClient_QueueSetForProcessing_Call) Return(s string, err error) *mockAwsClient_QueueSetForProcessing_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockAwsClient_QueueSetForProcessing_Call) RunAndReturn(run func(ctx context.Context, scannedCaseResponse *sirius.ScannedCaseResponse, fileName string) (string, error)) *mockAwsClient_QueueSetForProcessing_Call {
	_c.Call.Return(run)
	return _c
}

// newMockWorker creates a new instance of mockWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockWorker(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockWorker {
	mock := &mockWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockWorker is an autogenerated mock type for the worker type
type mockWorker struct {
	mock.Mock
}

type mockWorker_Expecter struct {
	mock *mock.Mock
}

func (_m *mockWorker) EXPECT() *mockWorker_Expecter {
	return &mockWorker_Expecter{mock: &_m.Mock}
}

// Process provides a mock function for the type mockWorker
func (_mock *mockWorker) Process(ctx context.Context, bodyStr string) (*sirius.ScannedCaseResponse, error) {
	ret := _mock.Called(ctx, bodyStr)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 *sirius.ScannedCaseResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*sirius.ScannedCaseResponse, error)); ok {
		return returnFunc(ctx, bodyStr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *sirius.ScannedCaseResponse); ok {
		r0 = returnFunc(ctx, bodyStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sirius.ScannedCaseResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, bodyStr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockWorker_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type mockWorker_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - bodyStr string
func (_e *mockWorker_Expecter) Process(ctx interface{}, bodyStr interface{}) *mockWorker_Process_Call {
	return &mockWorker_Process_Call{Call: _e.mock.On("Process", ctx, bodyStr)}
}

func (_c *mockWorker_Process_Call) Run(run func(ctx context.Context, bodyStr string)) *mockWorker_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockWorker_Process_Call) Return(scannedCaseResponse *sirius.ScannedCaseResponse, err error) *mockWorker_Process_Call {
	_c.Call.Return(scannedCaseResponse, err)
	return _c
}

func (_c *mockWorker_Process_Call) RunAndReturn(run func(ctx context.Context, bodyStr string) (*sirius.ScannedCaseResponse, error)) *mockWorker_Process_Call {
	_c.Call.Return(run)
	return _c
}
