FROM golang:1.24-bookworm

RUN apt-get update && apt-get install -y netcat-openbsd libxml2-dev

WORKDIR /app/service-app

COPY go.mod .
COPY go.sum .

RUN go mod download

RUN go install github.com/pact-foundation/pact-go/v2@v2.2.0 \
  && pact-go -l DEBUG install
