// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"
	"io"
	"net/http"

	"github.com/ministryofjustice/opg-scanning/internal/auth"
	"github.com/ministryofjustice/opg-scanning/internal/sirius"
	mock "github.com/stretchr/testify/mock"
)

// newMockAuth creates a new instance of mockAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAuth {
	mock := &mockAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockAuth is an autogenerated mock type for the Auth type
type mockAuth struct {
	mock.Mock
}

type mockAuth_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAuth) EXPECT() *mockAuth_Expecter {
	return &mockAuth_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type mockAuth
func (_mock *mockAuth) Authenticate(w http.ResponseWriter, r *http.Request) (auth.User, string, error) {
	ret := _mock.Called(w, r)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 auth.User
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request) (auth.User, string, error)); ok {
		return returnFunc(w, r)
	}
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request) auth.User); ok {
		r0 = returnFunc(w, r)
	} else {
		r0 = ret.Get(0).(auth.User)
	}
	if returnFunc, ok := ret.Get(1).(func(http.ResponseWriter, *http.Request) string); ok {
		r1 = returnFunc(w, r)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(http.ResponseWriter, *http.Request) error); ok {
		r2 = returnFunc(w, r)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockAuth_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type mockAuth_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *mockAuth_Expecter) Authenticate(w interface{}, r interface{}) *mockAuth_Authenticate_Call {
	return &mockAuth_Authenticate_Call{Call: _e.mock.On("Authenticate", w, r)}
}

func (_c *mockAuth_Authenticate_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *mockAuth_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockAuth_Authenticate_Call) Return(user auth.User, s string, err error) *mockAuth_Authenticate_Call {
	_c.Call.Return(user, s, err)
	return _c
}

func (_c *mockAuth_Authenticate_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request) (auth.User, string, error)) *mockAuth_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// UseCheckAuth provides a mock function for the type mockAuth
func (_mock *mockAuth) UseCheckAuth(next http.Handler) http.HandlerFunc {
	ret := _mock.Called(next)

	if len(ret) == 0 {
		panic("no return value specified for UseCheckAuth")
	}

	var r0 http.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func(http.Handler) http.HandlerFunc); ok {
		r0 = returnFunc(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}
	return r0
}

// mockAuth_UseCheckAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UseCheckAuth'
type mockAuth_UseCheckAuth_Call struct {
	*mock.Call
}

// UseCheckAuth is a helper method to define mock.On call
//   - next http.Handler
func (_e *mockAuth_Expecter) UseCheckAuth(next interface{}) *mockAuth_UseCheckAuth_Call {
	return &mockAuth_UseCheckAuth_Call{Call: _e.mock.On("UseCheckAuth", next)}
}

func (_c *mockAuth_UseCheckAuth_Call) Run(run func(next http.Handler)) *mockAuth_UseCheckAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.Handler
		if args[0] != nil {
			arg0 = args[0].(http.Handler)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockAuth_UseCheckAuth_Call) Return(handlerFunc http.HandlerFunc) *mockAuth_UseCheckAuth_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *mockAuth_UseCheckAuth_Call) RunAndReturn(run func(next http.Handler) http.HandlerFunc) *mockAuth_UseCheckAuth_Call {
	_c.Call.Return(run)
	return _c
}

// newMockAwsClient creates a new instance of mockAwsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAwsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAwsClient {
	mock := &mockAwsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockAwsClient is an autogenerated mock type for the AwsClient type
type mockAwsClient struct {
	mock.Mock
}

type mockAwsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAwsClient) EXPECT() *mockAwsClient_Expecter {
	return &mockAwsClient_Expecter{mock: &_m.Mock}
}

// PersistFormData provides a mock function for the type mockAwsClient
func (_mock *mockAwsClient) PersistFormData(ctx context.Context, body io.Reader, docType string) (string, error) {
	ret := _mock.Called(ctx, body, docType)

	if len(ret) == 0 {
		panic("no return value specified for PersistFormData")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, string) (string, error)); ok {
		return returnFunc(ctx, body, docType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, string) string); ok {
		r0 = returnFunc(ctx, body, docType)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.Reader, string) error); ok {
		r1 = returnFunc(ctx, body, docType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAwsClient_PersistFormData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PersistFormData'
type mockAwsClient_PersistFormData_Call struct {
	*mock.Call
}

// PersistFormData is a helper method to define mock.On call
//   - ctx context.Context
//   - body io.Reader
//   - docType string
func (_e *mockAwsClient_Expecter) PersistFormData(ctx interface{}, body interface{}, docType interface{}) *mockAwsClient_PersistFormData_Call {
	return &mockAwsClient_PersistFormData_Call{Call: _e.mock.On("PersistFormData", ctx, body, docType)}
}

func (_c *mockAwsClient_PersistFormData_Call) Run(run func(ctx context.Context, body io.Reader, docType string)) *mockAwsClient_PersistFormData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAwsClient_PersistFormData_Call) Return(s string, err error) *mockAwsClient_PersistFormData_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockAwsClient_PersistFormData_Call) RunAndReturn(run func(ctx context.Context, body io.Reader, docType string) (string, error)) *mockAwsClient_PersistFormData_Call {
	_c.Call.Return(run)
	return _c
}

// PersistSetData provides a mock function for the type mockAwsClient
func (_mock *mockAwsClient) PersistSetData(ctx context.Context, body []byte) (string, error) {
	ret := _mock.Called(ctx, body)

	if len(ret) == 0 {
		panic("no return value specified for PersistSetData")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (string, error)); ok {
		return returnFunc(ctx, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) string); ok {
		r0 = returnFunc(ctx, body)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAwsClient_PersistSetData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PersistSetData'
type mockAwsClient_PersistSetData_Call struct {
	*mock.Call
}

// PersistSetData is a helper method to define mock.On call
//   - ctx context.Context
//   - body []byte
func (_e *mockAwsClient_Expecter) PersistSetData(ctx interface{}, body interface{}) *mockAwsClient_PersistSetData_Call {
	return &mockAwsClient_PersistSetData_Call{Call: _e.mock.On("PersistSetData", ctx, body)}
}

func (_c *mockAwsClient_PersistSetData_Call) Run(run func(ctx context.Context, body []byte)) *mockAwsClient_PersistSetData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockAwsClient_PersistSetData_Call) Return(s string, err error) *mockAwsClient_PersistSetData_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockAwsClient_PersistSetData_Call) RunAndReturn(run func(ctx context.Context, body []byte) (string, error)) *mockAwsClient_PersistSetData_Call {
	_c.Call.Return(run)
	return _c
}

// QueueSetForProcessing provides a mock function for the type mockAwsClient
func (_mock *mockAwsClient) QueueSetForProcessing(ctx context.Context, scannedCaseResponse *sirius.ScannedCaseResponse, fileName string) (*string, error) {
	ret := _mock.Called(ctx, scannedCaseResponse, fileName)

	if len(ret) == 0 {
		panic("no return value specified for QueueSetForProcessing")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sirius.ScannedCaseResponse, string) (*string, error)); ok {
		return returnFunc(ctx, scannedCaseResponse, fileName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sirius.ScannedCaseResponse, string) *string); ok {
		r0 = returnFunc(ctx, scannedCaseResponse, fileName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sirius.ScannedCaseResponse, string) error); ok {
		r1 = returnFunc(ctx, scannedCaseResponse, fileName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAwsClient_QueueSetForProcessing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueueSetForProcessing'
type mockAwsClient_QueueSetForProcessing_Call struct {
	*mock.Call
}

// QueueSetForProcessing is a helper method to define mock.On call
//   - ctx context.Context
//   - scannedCaseResponse *sirius.ScannedCaseResponse
//   - fileName string
func (_e *mockAwsClient_Expecter) QueueSetForProcessing(ctx interface{}, scannedCaseResponse interface{}, fileName interface{}) *mockAwsClient_QueueSetForProcessing_Call {
	return &mockAwsClient_QueueSetForProcessing_Call{Call: _e.mock.On("QueueSetForProcessing", ctx, scannedCaseResponse, fileName)}
}

func (_c *mockAwsClient_QueueSetForProcessing_Call) Run(run func(ctx context.Context, scannedCaseResponse *sirius.ScannedCaseResponse, fileName string)) *mockAwsClient_QueueSetForProcessing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sirius.ScannedCaseResponse
		if args[1] != nil {
			arg1 = args[1].(*sirius.ScannedCaseResponse)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAwsClient_QueueSetForProcessing_Call) Return(MessageID *string, err error) *mockAwsClient_QueueSetForProcessing_Call {
	_c.Call.Return(MessageID, err)
	return _c
}

func (_c *mockAwsClient_QueueSetForProcessing_Call) RunAndReturn(run func(ctx context.Context, scannedCaseResponse *sirius.ScannedCaseResponse, fileName string) (*string, error)) *mockAwsClient_QueueSetForProcessing_Call {
	_c.Call.Return(run)
	return _c
}

// newMockSiriusClient creates a new instance of mockSiriusClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSiriusClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSiriusClient {
	mock := &mockSiriusClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockSiriusClient is an autogenerated mock type for the SiriusClient type
type mockSiriusClient struct {
	mock.Mock
}

type mockSiriusClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSiriusClient) EXPECT() *mockSiriusClient_Expecter {
	return &mockSiriusClient_Expecter{mock: &_m.Mock}
}

// AttachDocument provides a mock function for the type mockSiriusClient
func (_mock *mockSiriusClient) AttachDocument(ctx context.Context, data *sirius.ScannedDocumentRequest) (*sirius.ScannedDocumentResponse, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for AttachDocument")
	}

	var r0 *sirius.ScannedDocumentResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sirius.ScannedDocumentRequest) (*sirius.ScannedDocumentResponse, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sirius.ScannedDocumentRequest) *sirius.ScannedDocumentResponse); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sirius.ScannedDocumentResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sirius.ScannedDocumentRequest) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockSiriusClient_AttachDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachDocument'
type mockSiriusClient_AttachDocument_Call struct {
	*mock.Call
}

// AttachDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - data *sirius.ScannedDocumentRequest
func (_e *mockSiriusClient_Expecter) AttachDocument(ctx interface{}, data interface{}) *mockSiriusClient_AttachDocument_Call {
	return &mockSiriusClient_AttachDocument_Call{Call: _e.mock.On("AttachDocument", ctx, data)}
}

func (_c *mockSiriusClient_AttachDocument_Call) Run(run func(ctx context.Context, data *sirius.ScannedDocumentRequest)) *mockSiriusClient_AttachDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sirius.ScannedDocumentRequest
		if args[1] != nil {
			arg1 = args[1].(*sirius.ScannedDocumentRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockSiriusClient_AttachDocument_Call) Return(scannedDocumentResponse *sirius.ScannedDocumentResponse, err error) *mockSiriusClient_AttachDocument_Call {
	_c.Call.Return(scannedDocumentResponse, err)
	return _c
}

func (_c *mockSiriusClient_AttachDocument_Call) RunAndReturn(run func(ctx context.Context, data *sirius.ScannedDocumentRequest) (*sirius.ScannedDocumentResponse, error)) *mockSiriusClient_AttachDocument_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCaseStub provides a mock function for the type mockSiriusClient
func (_mock *mockSiriusClient) CreateCaseStub(ctx context.Context, data *sirius.ScannedCaseRequest) (*sirius.ScannedCaseResponse, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateCaseStub")
	}

	var r0 *sirius.ScannedCaseResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sirius.ScannedCaseRequest) (*sirius.ScannedCaseResponse, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sirius.ScannedCaseRequest) *sirius.ScannedCaseResponse); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sirius.ScannedCaseResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sirius.ScannedCaseRequest) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockSiriusClient_CreateCaseStub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCaseStub'
type mockSiriusClient_CreateCaseStub_Call struct {
	*mock.Call
}

// CreateCaseStub is a helper method to define mock.On call
//   - ctx context.Context
//   - data *sirius.ScannedCaseRequest
func (_e *mockSiriusClient_Expecter) CreateCaseStub(ctx interface{}, data interface{}) *mockSiriusClient_CreateCaseStub_Call {
	return &mockSiriusClient_CreateCaseStub_Call{Call: _e.mock.On("CreateCaseStub", ctx, data)}
}

func (_c *mockSiriusClient_CreateCaseStub_Call) Run(run func(ctx context.Context, data *sirius.ScannedCaseRequest)) *mockSiriusClient_CreateCaseStub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sirius.ScannedCaseRequest
		if args[1] != nil {
			arg1 = args[1].(*sirius.ScannedCaseRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockSiriusClient_CreateCaseStub_Call) Return(scannedCaseResponse *sirius.ScannedCaseResponse, err error) *mockSiriusClient_CreateCaseStub_Call {
	_c.Call.Return(scannedCaseResponse, err)
	return _c
}

func (_c *mockSiriusClient_CreateCaseStub_Call) RunAndReturn(run func(ctx context.Context, data *sirius.ScannedCaseRequest) (*sirius.ScannedCaseResponse, error)) *mockSiriusClient_CreateCaseStub_Call {
	_c.Call.Return(run)
	return _c
}
