// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sirius

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// newMockDoer creates a new instance of mockDoer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDoer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDoer {
	mock := &mockDoer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockDoer is an autogenerated mock type for the doer type
type mockDoer struct {
	mock.Mock
}

type mockDoer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoer) EXPECT() *mockDoer_Expecter {
	return &mockDoer_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type mockDoer
func (_mock *mockDoer) Do(request *http.Request) (*http.Response, error) {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (*http.Response, error)); ok {
		return returnFunc(request)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = returnFunc(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = returnFunc(request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockDoer_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type mockDoer_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - request *http.Request
func (_e *mockDoer_Expecter) Do(request interface{}) *mockDoer_Do_Call {
	return &mockDoer_Do_Call{Call: _e.mock.On("Do", request)}
}

func (_c *mockDoer_Do_Call) Run(run func(request *http.Request)) *mockDoer_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockDoer_Do_Call) Return(response *http.Response, err error) *mockDoer_Do_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *mockDoer_Do_Call) RunAndReturn(run func(request *http.Request) (*http.Response, error)) *mockDoer_Do_Call {
	_c.Call.Return(run)
	return _c
}
